# Generated by Django 4.2.6 on 2023-10-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('street1', models.CharField(max_length=50)),
                ('street2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('postal_code', models.IntegerField()),
                ('add_information', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'BillingAddress',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('phone', models.IntegerField()),
                ('booking_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
                ('location_name', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Destination',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_percentage', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='')),
                ('country_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('real_price', models.CharField(max_length=20)),
                ('cut_of_price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('location_name', models.CharField(max_length=20)),
                ('people', models.IntegerField()),
                ('no_of_day', models.CharField(max_length=20)),
                ('no_of_night', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('detail_desc', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('amount', models.IntegerField()),
                ('package_cost', models.IntegerField()),
                ('dedicated_tour_guide', models.IntegerField()),
                ('insurance_cost', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
