# Generated by Django 4.2.6 on 2023-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
                ('location_name', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Destination',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('location_name', models.CharField(max_length=20)),
                ('people', models.IntegerField()),
                ('no_of_day', models.IntegerField()),
                ('price', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Package',
            },
        ),
    ]
