# Generated by Django 4.2.6 on 2023-11-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='new',
            field=models.CharField(default='dinne', max_length=20),
        ),
    ]
