# Generated by Django 4.2.6 on 2023-11-06 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 6, 10, 0, 31, 937131), null=True),
        ),
    ]
