# Generated by Django 4.2.6 on 2023-11-06 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 10, 24, 47, 580281), verbose_name='XYZ DateTime'),
        ),
    ]
