# Generated by Django 4.2.6 on 2023-11-07 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0015_alter_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 7, 22, 9, 26, 497036)),
        ),
    ]
