# Generated by Django 4.2.6 on 2023-11-08 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_rename_product_price_shop_product_price_del_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 9, 57, 35, 934013)),
        ),
    ]
