# Generated by Django 4.2.6 on 2023-11-08 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0021_alter_booking_booking_date_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 10, 44, 37, 213151)),
        ),
    ]
