# Generated by Django 4.2.6 on 2023-11-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0025_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='new',
        ),
    ]
