# Generated by Django 4.2.6 on 2023-11-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0028_remove_booking_user_booking_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=15)),
            ],
        ),
    ]
